<?php

namespace AppBundle\Repository;

use AppBundle\AppBundle;
use AppBundle\Entity\Payment;
use Doctrine\ORM\Mapping\Entity;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPayments($dateFrom, $dateTo, $select,$where)
    {
        $entityManager = $this->getEntityManager();
        $date = new \DateTime("{$dateFrom}");
        $dateEnd = new \DateTime("$dateTo");
        $query = $entityManager->createQuery(
            "SELECT ".$select." FROM AppBundle\Entity\Payment as pay WHERE ".$where." pay.date BETWEEN :start AND :end ")
            ->setParameter('start', $date->format('Y-m-d'))
            ->setParameter('end', $dateEnd->format('Y-m-d'));
        return $query->getResult();
    }
    public function getMaxUserPayments($dateFrom, $dateTo)
    {
        $entityManager = $this->getEntityManager();
        $date = new \DateTime("{$dateFrom}");
        $dateEnd = new \DateTime("$dateTo");
        $query = $entityManager->createQuery(
            "SELECT pay.userId, SUM(pay.price) FROM AppBundle\Entity\Payment as pay WHERE (pay.status = 'Paid' AND pay.date BETWEEN :start AND :end) GROUP BY pay.userId  ")
            ->setParameter('start', $date->format('Y-m-d'))
            ->setParameter('end', $dateEnd->format('Y-m-d'));
        return $query->getResult();
    }
}
